sudo: required
language: bash
services:
  - docker
before_script:
  - docker build . --tag=esnerda.wr-intercom
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true